navbar:
  blog_title: Tetryl
  ground_glass:
    enable: true
index:
  banner_img: https://img.mgwhw.com/upload/343/2020/11-18/20201118154714490740_small.jpg
  banner_img_height: 103
  slogan:
    text: Hello, this is Tetryl !
post:
  banner_img: /images/uploads/mmexport1602581319886.webp
  banner_img_height: 80
  default_index_img: /images/uploads/wallhaven-g8wvm7.webp
archive:
  banner_img: /images/uploads/8dd497ac-44b0-4e76-bf11-b7a7df7a5a0b.jpeg
  banner_img_height: 80
  subtitle: null
category:
  banner_img: /images/uploads/b8547f95-ae7e-45e4-9bbe-e988056124a9.jpeg
  banner_img_height: 80
  subtitle: null
tag:
  banner_img: /images/uploads/1616421669417-wallhaven-1kkm2g.jpg
  banner_img_height: 80
  subtitle: null
about:
  banner_img: /images/uploads/wallhaven-pkkr2.webp
  banner_img_height: 80
  subtitle: null
  avatar: https://img.syt5.com/2020/0901/20200901102746916.jpg
  name: Tetryl
  intro: Removing the barriers to the knowledge
links:
  banner_img: /images/uploads/1616421416500-wallhaven-rddv31.jpg
  banner_img_height: 80
  subtitle: null
  items:
    - title: Fluid Repo
      intro: 主题 GitHub 仓库
      link: https://github.com/fluid-dev/hexo-theme-fluid
      avatar: /img/favicon.png
    - title: Overleaf
      intro: Tetryl' private latex
      link: https://tex.tetryl.top/project
      avatar: https://avatars.githubusercontent.com/u/6359919?s=64&v=4
